core/urls.py
from django.urls import path
from core.views import (
    Item,
    ItemDetailView,
    MotifView,
    DemandeSummaryView,
    DemandeView,
    add_to_demande,
    remove_from_demande,
    remove_single_item_from_demande,
    demande_traffiche,
    welcome_admin,
    demande_affiche,
    demande_traitement_edit,
    ImprimePdf,
    rapport_mensuel,
    intro,
    delete
)
app_name = 'core'

urlpatterns = [
    path('', intro, name='intro'),
    path('home/', welcome_admin, name='home'),
    path('delete/<int:id>', delete, name='delete'),
    path('demandes/', demande_affiche, name='demandes'), 
    path('demande-summary/', DemandeSummaryView.as_view(), name='demande-summary'),
    path('motifs/', MotifView.as_view(), name='motifs'),
    path('demande/<int:id>', demande_traitement_edit, name='demande'),
    path('motif/<slug>/', ItemDetailView.as_view(), name='motif'),
    path('add-to-demande/<slug>/', add_to_demande, name='add-to-demande'),
    path('remove-from-demande/<slug>/', remove_from_demande, name='remove-from-demande'),
    path('remove-item-from-demande/<slug>/', remove_single_item_from_demande,
         name='remove-single-item-from-demande'),
    path('demandes/traite/', demande_traffiche, name="dtraite"),
    path('demandes/traite/pdf/<int:id>', ImprimePdf, name="pdf_view"), #pdf print
    path('rapport/', rapport_mensuel, name='rapport'),
]

pydemande/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from core.views import logoutTlogin

urlpatterns = [
    
    path('', include('core.urls')), 
    
    re_path(r'', include('user_sessions.urls', 'user_sessions')), #user sessions
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', logoutTlogin, name='logout'),
    path('demande-summary/logout/', lambda request: redirect('logout', permanent=False)),
    path('rapport/logout/', lambda request: redirect('logout', permanent=False)),
    path('demandes/logout/', lambda request: redirect('logout', permanent=False)),
    path('motifs/logout/', lambda request: redirect('logout', permanent=False)),
    path('motif/logout/', lambda request: redirect('logout', permanent=False)),
    path('demande/logout/', lambda request: redirect('logout', permanent=False)),
    path('demandes/traite/logout/', lambda request: redirect('logout', permanent=False)),
    path(r'', include('qr_code.urls', namespace="qr_code")),
    
    
]

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Admin</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'polls/vendor/fontawesome-free/css/all.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'polls/sb-admin-2.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.js" %}"></script>
    <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.charts.js" %}"></script>
    
  
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
    <script type="text/javascript" src="{% static "fusioncharts/themes/fusioncharts.theme.umber.js" %}"></script>

</head>
<body id="page-top">
<!-- Page Wrapper -->
  <div id="wrapper">

      {% include 'sidebar.html' %}
       <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

          {% include 'navbar.html' %}
           <!-- Begin Page Content -->
        <div class="container-fluid">
        <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div id="message" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button id="btnclick" type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        </div>
            {% block content %}


            {% endblock %}
        </div>
      </div>
    </div>
  </div>

 <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>


<!-- Logout Modal-->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deconnexion?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">cliquez sur « Logout » si vous êtes prêt à terminer votre session en cours.</div>
        <div class="modal-footer">
          <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-success" href="{% url 'logout' %}" value="logout">Logout</a>
        </div>
      </div>
    </div>
  </div>


<!-- Footer -->
  <footer class="bg-dark ">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2021 - LES CENTAURES ROUTIERS - V1.0</div>
    </div>
  </footer>

<!-- Bootstrap core JavaScript-->
  <script src="{% static 'js/jquery/jquery.min.js' %}"> </script>
  <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script>
    $(function() {
  setTimeout(function() { $("#message").fadeOut(1500); }, 5000)
  $('#btnclick').click(function() {
  $('#message').show();
  setTimeout(function() { $("#message").fadeOut(1500); }, 5000)
  })
  })
  </script>
  <!-- Core plugin JavaScript-->
  <script src="{% static 'js/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'js/chart.js/Chart.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

  <!-- Page level custom scripts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  
</body>

</html>

templates/charts.html
{% extends 'base.html' %}
{% block content %}

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Rapport Temps réel</h1>
          

          <!-- Content Row -->
          <div class="row">

            <div class="col-md-12">

              <!-- Area Chart -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-danger">Graphe d'évolution frais chauffeurs.</h6>
                </div>
                <div class="card-body">
                  <div class="chart-area">
                    <div id="chart-1">{{ output|safe }}</div>
                  </div>
                  
                </div>
              </div>
            </div>

            
            
          </div>
          

{% endblock %}

templates/demande.html
{% extends "base.html" %}
{%load crispy_forms_tags %}
{% block content %}

  <main >
    <div class="container wow fadeIn">
      <u><h2 class="my-5 h2 text-center">ETAPE 3/3:  REMPLIR L'EN-TETE DE LA DEMANDE</h2></u>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              {{ form | crispy  }}

              <!--<div class='hideable_shipping_form'>

              <!--  <div class="md-form mb-5">
              <!--    {{form.num_releve }}
              <!--    
              <!--  </div>

              <!--  <div class="md-form mb-5">
              <!--    {{form.code_vehicule }}
              <!--  </div>

              <!--  <div class="md-form mb-5">
              <!--    {{form.code_remorque }}
              <!--  </div>

              <!--  <div class="md-form mb-5">
              <!--    {{form.imat_véhicule }}
              <!--  </div>

              <!--  <div class="md-form mb-5">
              <!--    {{form.imat_remorque }}
              <!--  </div>
              <!--  

              <!--  
              <!--  <div class="md-form mb-5">
              <!--  
              <!--    {{form.code_activite }}
              <!--  </div>
              <!--  
              <!--  <label>Libelle activité</label>
              <!--  <div class="md-form mb-5">
              <!--  
              <!--    {{form.libelle_activite }}
              <!--  </div>

              <!--  
              <!--  <div class="custom-control custom-checkbox">
              <!--  <label>A rembourser</label>
              <!--    {{ form.a_rembourser }}
              <!--  </div>

              <!--</div>

              <!--

              <!--<hr>

              <!--

              <!--

              <!--  

              <!--</div>-->

            

           

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Soumettre ma demande</button>

            </form>

          </div>

        </div>

        

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

templates/demande_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">
    <u><h2 class="my-5 h2 text-center">ETAPE 2/3:  VERIFIER MES MOTIFS</h2></u>
    <div class="table-responsive text-nowrap">
    <h2>Aperçu des Motifs sélectionés</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Libelle</th>
            <th scope="col">Prix unitaire</th>
            <th scope="col">Quantité</th>
            <th scope="col">Prix Total Motif</th>
        </tr>
        </thead>
        <tbody>
        {% for demande_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ demande_item.item.libelle }}</td>
            <td>{{ demande_item.item.prix }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-demande' demande_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ demande_item.quantite }}
                <a href="{% url 'core:add-to-demande' demande_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            
                {{ demande_item.get_total_item_price }}F
            
            <a style='color: red;' href="{% url 'core:remove-from-demande' demande_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Vous n'avez pas de motif sélectioné</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='{% url "core:motifs"%}'>Choisir d'autres motifs</a>
            </td>
        </tr>
        {% endfor %}
        
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Total</b></td>
            <td><b>{{ object.get_total }}F</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-success float-right ml-2' href='{%url "core:demande" object.id%}'>Etape suivante</a>
            <a class='btn btn-primary float-right  ml-2' href='{%url "core:motifs"%}'>Choisir d'autres motifs</a>
            <a class='btn btn-danger float-right text-white  ml-2'  data-toggle="modal" data-target="#deleteModal">Annuler la demande</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
    <!-- Delete Modal-->
 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Supprimer?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Voulez-vous vraiment supprimer la demande ?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
            <a class="btn btn-primary" href="{%url 'core:delete' object.id  %}" >Supprimer</a>
        </div>
      </div>
    </div>
  </div>
  </main>

{% endblock content %}

templates/home.html
<header>
{%load static%}
  <div class="wrapper">
    <div class="logo">
      <img src="{% static 'polls/images/LogogroupeCentaure.png' %}"
        alt="logo"
        style="width: 120px;
height: 50px;"/>
    </div>
    <ul class="nav-area">
      <li><a href="/admin">Admin</a></li>
    </ul>
  </div>
  <div class="welcome-text">
    <h1>Bienvenue sur DFC Centaures V 1.0 !</h1>
    <a href="{% url 'core:home' %}">Démarrer</a>
  </div>
  <style>
    * {
      margin: 0;
      padding: 0;
    }
    body {
      font-family: "Lato", sans-serif;
    }
    .wrapper {
      width: 1170px;
      margin: auto;
    }
    header {
      background: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)),
        url({% static 'polls/images/background3.jpg' %});
      height: 100vh;
      -webkit-background-size: cover;
      background-size: cover;
      background-position: center center;
      position: relative;
    }
    .nav-area {
      float: right;
      list-style: none;
      margin-top: 30px;
    }
    .nav-area li {
      display: inline-block;
    }
    .nav-area li a {
      color: #fff;
      text-decoration: none;
      padding: 5px 20px;
      font-family: poppins;
      font-size: 16px;
      text-transform: uppercase;
    }
    .nav-area li a:hover {
      background: #fff;
      color: #d51a1d;
    }
    .logo {
      float: left;
    }
    .logo img {
      width: 100%;
      padding: 15px 0;
    }
    .welcome-text {
      position: absolute;
      width: 600px;
      height: 300px;
      margin: 20% 30%;
      text-align: center;
    }
    .welcome-text h1 {
      text-align: center;
      color: #fff;
      text-transform: uppercase;
      font-size: 60px;
    }
    .welcome-text a {
      border: 1px solid #fff;
      padding: 10px 25px;
      text-decoration: none;
      text-transform: uppercase;
      font-size: 14px;
      margin-top: 20px;
      display: inline-block;
      color: #fff;
    }
    .welcome-text a:hover {
      background: #d51a1d;
      color: #fff;
    }

    /*resposive*/

    @media (max-width: 600px) {
      .wrapper {
        width: 100%;
      }
      .logo {
        float: none;
        width: 50%;
        text-align: center;
        margin: auto;
      }
      img {
        width: ;
      }
      .nav-area {
        float: none;
        margin-top: 0;
      }
      .nav-area li a {
        padding: 5px;
        font-size: 11px;
      }
      .nav-area {
        text-align: center;
      }
      .welcome-text {
        width: 100%;
        height: auto;
        margin: 30% 0;
      }
      .welcome-text h1 {
        font-size: 30px;
      }
    }
  </style>
</header>

templates/index.html
{% extends 'base.html' %}






          {% block content %}

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Tableau de bord</h1>
            
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-8">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Demande frais chauffeur non traitées</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ nb_dmd }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-car fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br/>
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-8">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Demande en cours non soumise</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ nb_dmds }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-car fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <br>
        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-8">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Demande frais chauffeur traitées</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                          <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ nb_dmdt }}</div>
                        </div>

                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-archive fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pending Requests Card Example -->
            <!--<div class="col-xl-6 col-md-12 mb-8">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Demande de carburant traitées</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ nb_carbt }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-archive fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>-->
          </div>
          <br>
            

          <!-- Content Row -->

          

          

       {% endblock %}

templates/motif.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
  <u><h2 class="h3 mb-0 text-center text-gray-800">AJOUTER LE MOTIF A MA DEMANDE</h2></u>
    <div class="container dark-grey-text mt-5">
        
      <!--Grid row-->
      <div class="row wow fadeIn">
        
        
        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
            
              <a href="">
                <h1><span class="badge orange mr-4">{{ object.libelle }}</span></h2>
              </a>
            </div>

            <p class="lead">
              
              <span>{{ object.prix }}</span>
            
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <a href="{{ object.get_add_to_demande_url }}" class="btn btn-primary btn-md my-0 p">
              Ajouter à la demande
              <i class="fas fa-plus ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_demande_url }}" class="btn btn-danger btn-md my-0 p">
              Supprimer de la demande
              <i class="fas fa-trash ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

     

      

    </div>
  </main>

{% endblock content %}

templates/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul
  class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion"
  id="accordionSidebar"
>
  <!-- Sidebar - Brand -->
  <a
    class="sidebar-brand d-flex align-items-center justify-content-center"
    href="/home"
  >
    <div class="sidebar-brand-icon">
      <img
        src="{% static 'polls/images/LogogroupeCentaure.png' %}"
        alt="logo"
        style="width: 120px;
height: 50px;"
      />
    </div>
    <!--<div class="sidebar-brand-text mx-3">Admin <sup>2</sup></div>-->
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0" />

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'core:home'%}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Accueil</span></a
    >
  </li>

{%if user.is_superuser%}
  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'core:rapport' %}">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Rapport Temps Réel</span></a>
  </li>
{%endif%}
{% if user.is_staff %}
  <li class="nav-item">
    <a class="nav-link" href="/admin">
      <i class="fas fa fa-unlock-alt"></i>
      <span>Page admin</span></a>
  </li>
  {% endif %}

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'core:demandes' %}">
      <i class="fas fa-fw fa-table"></i>
      <span>Suivi demandes en cours</span></a
    >
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'core:motifs'%}">
      <i class="fa fa-plus" aria-hidden="true"></i>
      <span>Faire ma demande</span></a
    >
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'core:demande-summary'%}">
      <i class="fa fa-database" aria-hidden="true"></i>
      <span>Mes demandes enregistrées</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block" />

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->

templates/tables2.html
     

     



        {% extends 'base.html' %}
         {% block content %}

          <!-- Page Heading -->
          <div class="row">
          <div class="col-md-8">
               <h1 class="h3 mb-2 text-gray-800">Les demandes de frais d'exploitation</h1>
          <p class="mb-4">....</p>
          </div>
          <div class="col-md-4">
              <br>
              <a href="{% url 'core:dtraite' %} ">
               <button class="btn btn-primary" type="button"  >Les demandes Traitées</button>
            </a>

          </div>


          </div>


          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Suivi de frais chauffeurs.</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
              
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                   <tr>
                     <th>Date demande</th>
                      <th>Numéro relevé</th>
                      <th>Demandeur</th>
                      <th>Code Activité</th>
                     <!--  <th>Libelle</th>-->
                     
                      

                      <th>Total</th>
                     
                      <th>Statut</th>
                      
                     
                       <th>Action</th>
                  
                      
                      
                 
                    </tr>
                  </thead>
                  <tbody>

                      {% for item in query_results %}
                      {% if user.username == item.user.username %}
    <tr>
        <td>{{ item.demande_date }}</td>
        <td>{{ item.num_releve }}</td>
        <td>{{ item.user }}</td>
        <td>{{ item.code_activite }}</td>
        <!--<td>{{ item.libelle_activite }}</td>-->
      
        
        
        <td>{{ item.montant_ttc }}</td>
       
        {% if item.traite == False %}
        <td class="text-danger">En attente </td>
        <td><i class="fa fa-ban" aria-hidden="true"></i></td>
        {% elif  item.soumis == False %}
        <td class="text-danger">Non soumis </td>
        <td><i class="fa fa-ban" aria-hidden="true"></i></td>
        {%  else%}
        <td class="text-success">Validé </td>
        <td>
          <a href="pdf/{{item.id}}">
             <button class="btn btn-success" type="button" value="{{ item.id }}" ><i class="fa fa-download" aria-hidden="true">Telecharger</i></button>
          </a>
        </td>
        {%  endif %}
       <!-- <td>
        {% if user.is_superuser and item.traite == False %}
            <a href="{{ item.get_detail_url }}  ">
               <button class="btn btn-success" type="button" value="{{ item.id }}" >Traitement</button>
            </a>
        {% else %}
            <a href="#!">
               <button class="btn btn-dark disabled" type="button" value="" >Traitement</button>
            </a>

        {% endif %}
        </td>-->
    </tr>
    {%endif%}
    {% endfor %}
                  
                  </tbody>
                </table>
               
              </div>
            </div>
          </div>

        {% endblock %}